# Конфигурация сервера
server:
  # Номер порта - целое число.
  port: 3000
  
  # Адрес сервера - строка.
  host: '0.0.0.0'

# Конфигурация генератора
uid:
  # Длина генерируемого UID - целое число.
  length: 6

  # Алфавит для генерации UID - строка с перечнем символов.
  alphabet: '0123456789ABCDEFGHIJKLMNPQRSTUVWZYX'
